### ISSUE TITLE
fix CSS problem if frontend not loaded from webflow

### ISSUE THREAD

**Issue by Bartzi** [refugeehackathon/interpreteer-backend#14]
If the frontend is not loaded from webflow the CSS seems to be broken. It looks like this:
![interpreteer_error](https://cloud.githubusercontent.com/assets/2399349/10973967/186d4602-83e0-11e5-8524-67e0370134ff.png)

**Comment by johannesjasper** [comment]
'Fixed' it for now.
The problem is that each of the 2 elements side by side has 50%. There is a space between them however.
