### ISSUE TITLE
How to localize?

### ISSUE THREAD

**Issue by dahoo** [refugeehackathon/interpreteer-backend#28]
We could either use django's possibilities (if we keep the current way of serving html) or use a JS library such as [L20n](http://l20n.org/).

@refugeehackathon/interpreteer Opinions?

**Comment by hrantzsch** [comment]
I think we want to decouple our frontend and backend again. So the frontend would need to take care of localization on its own and without Django. (Right?)

**Comment by dahoo** [comment]
Since were using ember now, we should use something like ember-i18n
