### ISSUE TITLE
Switch to GeoDjango and PostGis

### ISSUE THREAD

**Issue by illing2005** [refugeehackathon/interpreteer-backend#39]

**Comment by illing2005** [comment]
If we only want to filter distances, this might be sufficient:
http://stackoverflow.com/questions/19703975/django-sort-by-distance#answer-26219292

**Comment by illing2005** [comment]
Any thoughts?

**Comment by hrantzsch** [comment]
That SO post looks good to me. You said GeoDjango is pretty heavy, right? Then it should be nice to avoid it.

**Comment by dahoo** [comment]
I'm with Hannes.
