### ISSUE TITLE
Add testing framework and continious integration

### ISSUE THREAD

**Issue by dahoo** [refugeehackathon/interpreteer-backend#41]
Travis CI is free for open source projects and integrates well with GitHub.

**Comment by illing2005** [comment]
@dahoo I tried to setup travis CI, but I don't have admin rights for the repository. 
Can you give me admin rights or enable travis ci for interpreteer-backend?

**Comment by dahoo** [comment]
Sure, I enabled the repository [here](https://travis-ci.org/refugeehackathon/interpreteer-backend) and you're also admin now. Haye you used TravisCI before? [Here](https://docs.travis-ci.com/user/languages/python) are the docs for Python.
